---
# Install vim on EC2 server
- name: "Install vim text editor"
  hosts: all
  become: yes
  
  tasks:
    - name: "Update package cache"
      yum:
        update_cache: yes
      when: ansible_os_family == "RedHat"
      
    - name: "Install vim"
      yum:
        name: vim
        state: present
      when: ansible_os_family == "RedHat"
      
    - name: "Verify vim installation"
      command: vim --version
      register: vim_version
      
    - name: "Display vim version"
      debug:
        msg: "✅ vim installed successfully: {{ vim_version.stdout_lines[0] }}"
